### ISSUE TITLE
Dragonflying Unhides Action Bar

### ISSUE THREAD

**Issue by kennywasafk** [Slothpala/MouseoverActionSettings#7]
Just wanted to mention that getting on a dragonflying mount unhides Action Bar 1 if you set it to mouseover with the addon. Would be perfect if there was a way to circumvent that. 

Otherwise thanks for your effort! Very lightweight and does what it needs to do.

**Comment by Slothpala** [comment]
Hey, this is intentional behavior with the default settings. In addition to hovering over the frame, you can also set triggers to display a module. By default, in addition to hovering, Action Bar 1 is also displayed when you are in combat or skyriding. 
You can customize these by clicking tweak and then selecting the triggers you want.

![Screenshot 2024-08-20 235619](https://github.com/user-attachments/assets/7c44cfe3-03e4-4c41-8dd6-c3cc48625806)

![Screenshot 2024-08-20 235627](https://github.com/user-attachments/assets/cd9a7cfe-4fd5-4e71-861c-abc51eb693d0)

**Comment by kennywasafk** [comment]
Oh apologies, it's a little hidden away so I didn't realise. Hope this post helps someone else who comes looking.
I'll close it now, thanks for your help and for developing the addon!
